image: Visual Studio 2017

version: 1.0.{build}

skip_non_tags: false
skip_tags: true

skip_commits:
  files:
    - '**/*.md'

branches:
  only:
    - master

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

install:
  - nuget install GitReleaseNotes.Portable -OutputDirectory %APPVEYOR_BUILD_FOLDER%\packages -Version 0.7.1

configuration:
  - Release

dotnet_csproj: 
  patch: true 
  file: '**\*.csproj' 
  version: '{version}' 
  assembly_version: '{version}' 
  file_version: '{version}'

before_build:
  - nuget restore ./NerdBotCore/NerdBotCore.sln

build:
  project: NerdBotCore/NerdBotCore.sln
  verbosity: minimal

after_build:
  - cmd: cd ./NerdBotCore/NerdBotHost/bin/%CONFIGURATION%/netcoreapp2.2
  - cmd: 7z a C:\projects\nerdbot-core\NerdBot-%APPVEYOR_BUILD_VERSION%.zip *.* -x!*.pdb -x!*.vhost.*
  - cmd: cd C:\projects\nerdbot-core\NerdBotCore\NerdBotCorePlugin\bin\%CONFIGURATION%\netcoreapp2.2
  - cmd: 7z a C:\projects\nerdbot-core\NerdBotCorePlugin-%APPVEYOR_BUILD_VERSION%.zip *.* -x!*.pdb -x!*.vhost.*
  - cmd: cd C:\projects\nerdbot-core\NerdBotCore\NerdBotGiphyPlugin\bin\%CONFIGURATION%\netcoreapp2.2
  - cmd: 7z a C:\projects\nerdbot-core\NerdBotGiphyPlugin-%APPVEYOR_BUILD_VERSION%.zip *.* -x!*.pdb -x!*.vhost.*
  - cmd: cd C:\projects\nerdbot-core\NerdBotCore\NerdBotRoastMePlugin\bin\%CONFIGURATION%\netcoreapp2.2
  - cmd: 7z a C:\projects\nerdbot-core\NerdBotRoastMePlugin-%APPVEYOR_BUILD_VERSION%.zip *.* -x!*.pdb -x!*.vhost.*
  - cmd: cd C:\projects\nerdbot-core\NerdBotCore\NerdBotScryFallPlugin\bin\%CONFIGURATION%\netcoreapp2.2
  - cmd: 7z a C:\projects\nerdbot-core\NerdBotScryFallPlugin-%APPVEYOR_BUILD_VERSION%.zip *.* -x!*.pdb -x!*.vhost.*
  - cmd: cd C:\projects\nerdbot-core\NerdBotCore\NerdBotUrbanDictPlugin\bin\%CONFIGURATION%\netcoreapp2.2
  - cmd: 7z a C:\projects\nerdbot-core\NerdBotUrbanDictPlugin-%APPVEYOR_BUILD_VERSION%.zip *.* -x!*.pdb -x!*.vhost.*

artifacts:
  - path: '*.zip'

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor C:\projects\nerdbot-core\NerdBotCore\NerdBotCore.sln

before_deploy:
  - ps: cd ${env:APPVEYOR_BUILD_FOLDER};
  - ps: .\packages\GitReleaseNotes.Portable.0.7.1\tools\GitReleaseNotes.exe . /OutputFile ReleaseNotes.md;
  - ps: ${env:release_description} = ( Get-Content -LiteralPath ReleaseNotes.md -Encoding UTF8 ) -join "`n";
  - ps: ${env:release_description} = ${env:release_description} + ".";

deploy:
  release: NerdBot-$(APPVEYOR_BUILD_VERSION)
  description: NerdBot build $(APPVEYOR_BUILD_VERSION).\n$(release_description)
  provider: GitHub
  auth_token:
    secure: EXRr3SxM7c0kVhOc5HAyMr4gUaCJA11QE/RbTNrqYil9WXKDqoQoigCfdD6ZjhDX # encrypted token from GitHub
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  tag: $(APPVEYOR_BUILD_VERSION)
  on:
    branch: 
      - master  # release from master branch only

